### PR TITLE
Disable load more when nothing to load #89

### PR DESCRIPTION
**Pull request by hitripod**

### CODE REVIEW

**Comment by shinglyu** [comment]
Great! 

You might have to add `hasNoLinkToShow: false` to `getInitialState()` too, they are on line 120 and 125. (We should clean up the `getInitialState()`someday, the `if` is quite ugly`)

**Comment by shinglyu** [comment]
Opened a follow up bug #101

**Comment by hitripod** [comment]
Added. Thanks for reminding

**Comment by shinglyu** [comment]
Thanks for contributing

**Comment by hitripod** [comment]
Any API to get the total number of the query result? Pagination is indeed more user-friendly.

``` javascript
//FIXME: Change this to pagination
```

**Comment by shinglyu** [comment]
Let's move the pagination discussion to https://github.com/shinglyu/moztrap-new-ui/issues/30

**Pull request merged**
