### PR TITLE
Refactor merge case suite view

### PR DESCRIPTION
**Pull request by yodalee**
So many change
Try to use common class in caseversion and suite case.

### CODE REVIEW

**Comment by shinglyu** [comment]
感恩大大 讚嘆大大

**Comment by yodalee** [comment]
http://otiai10.com/chino.gif

**Comment by yodalee** [comment]
http://img2.wikia.nocookie.net/__cb20150212104829/kancolle/images/e/e9/Russiaapproves.png

**Comment by yodalee** [comment]
image

**Comment by yodalee** [comment]
喔原來可以貼gif XDD
[LGTM](http://lgtm.in/i/caoU3ZJeq)

**Comment by shinglyu** [comment]
XDD

**Pull request merged**
